mall:
  local_effect_radius: 3500
  gravity_constant: 1.3
  global_multiplier: ["RICH", 0.8]

complejo_apartamentos:
  local_effect_radius: 1000
  gravity_constant: 1.15
  global_multiplier: ["WORK", 1.5]

parque_grande:
  local_effect_radius: 4000
  gravity_constant: 1.4
  global_multiplier: ["RICH", 1.7]
