mall:
  local_effect_radius: 3500
  gravity_constant: 25
  gravity_decay_exp: 2
  global_multiplier: ("RICH", 1.3)

complejo_apartamentos:
  local_effect_radius: 1000
  gravity_constant: 10
  gravity_decay_exp: 2
  global_multiplier: ("WORK", 1.5)

parque_grande:
  local_effect_radius: 4000
  gravity_constant: 20
  gravity_decay_exp: 1.5
  global_multiplier: ("RICH", 1.1)
