mall:
  local_effect_radius: 3500
  gravity_constant: 25
  global_multiplier: ["RICH", 1.3]

complejo_apartamentos:
  local_effect_radius: 1000
  gravity_constant: 10
  global_multiplier: ["WORK", 1.5]

parque_grande:
  local_effect_radius: 4000
  gravity_constant: 20
  global_multiplier: ["RICH", 1.1]
